In [4]:
friend_list=[]
while True:
    print("================================")
    print("1. 친구 리스트 출력")
    print("2. 친구 추가")
    print("3. 친구 삭제")
    print("4. 이름 변경")
    print("9. 종료")
    menu=int(input("메뉴를 입력하세요 : "))
    if menu==1:
        print(friend_list)
    elif menu ==2:
        name=input("이름을 입력하세요 : ")
        tel=input("전화번호를 입력하세요 : ")
        friend_list.append([name, tel])
    elif menu ==3:
        name=input("이름을 입력하세요 : ")
        for i in range(len(friend_list)):
            if friend_list[i][0]==name:
                del friend_list[i]
    elif menu ==4:
        name=input("이름을 입력하세요 : ")
        for i in range(len(friend_list)):
            if friend_list[i][0]==name:
                name_change=input("변경할 이름을 입력하세요 : ")
                friend_list[i][0]=name_change
    elif menu == 9:
        break
    else:
        print("다시 입력해주세요")
    print("================================")

1. 친구 리스트 출력
2. 친구 추가
3. 친구 삭제
4. 이름 변경
9. 종료
메뉴를 입력하세요 : 9


In [9]:
english_dict=dict()

english_dict["one"]="하나"
english_dict["two"]="둘"
english_dict["three"]="셋"

english_dict["하나"]="one"
english_dict["둘"]="two"
english_dict["셋"]="three"
word = input("단어를 입력하세요 :")
print(english_dict.get(word, "없음"))

단어를 입력하세요 :둘
two


In [7]:
english_dict=dict()

english_dict["one"]="하나"
english_dict["two"]="둘"
english_dict["three"]="셋"

word = input("단어를 입력하세요 :")
word.encode().isalpha() #한글인지 확인하기

단어를 입력하세요 :안녕


False

## 파일 복사하기

In [ ]:
filename1=input("원본 파일 이름을 입력하시오 : ")
filename2=input("복사 파일 이름을 입력하시오 : ")

infile = open(filename1, "rb")
outfile = open(filename2, "wb")

#입력파일에서 1024바이트씩 읽어서 출력파일에 쓴다.
while True:
    copy_buffer = infile.read(1024) #1024비트씩 읽기
    if not copy_buffer:
        break
    outfile.write(copy_buffer)

infile.close()
outfile.close()
print("복사완료")

## json 파일 다루기

In [14]:
import json
with open("C:/Users/pc/Main/Data_Analysis/test.json", "rb") as file:
    #json모듈을 임포트한 후, load 함수를 통해 데이터를 가져올 수 있음
    json_data=json.load(file)

print(json.dumps(json_data))

{"K5": {"price": "5000", "year": "2015"}, "Avante": {"price": "3000", "year": "2014"}}


In [16]:
print(json.dumps(json_data, indent="\t"))

{
	"K5": {
		"price": "5000",
		"year": "2015"
	},
	"Avante": {
		"price": "3000",
		"year": "2014"
	}
}


In [18]:
json_data["K5"]["price"]

'5000'

In [19]:
#데이터 수정하기
json_data["K5"]["price"]="7000"

In [20]:
json_data["K5"]["price"]

'7000'

In [22]:
## 다시 저장하기
with open("C:/Users/pc/Main/Data_Analysis/test.json", "w") as make_file:
    json.dump(json_data, make_file, indent="\t")

In [26]:
# 다시 읽기
with open("C:/Users/pc/Main/Data_Analysis/test.json", "r") as read_file:
    read_json=json.load(read_file)
print(json.dumps(read_json, indent="\t"))

{
	"K5": {
		"price": "7000",
		"year": "2015"
	},
	"Avante": {
		"price": "3000",
		"year": "2014"
	}
}


In [32]:
import json

car_group = dict()

k5 = dict()
k5["price"]="5000"
k5["year"]="2015"
car_group["K5"] = k5

avante=dict()
avante["price"]="3000"
avante["year"]="2014"
car_group["Avante"]=avante

#json파일로 저장
with open("C:/Users/pc/Main/Data_Analysis/test.json", 'w', encoding="utf-8") as make_file:
    json.dump(car_group, make_file, indent="\t")

In [33]:
#저장한 파일 출력
with open("C:/Users/pc/Main/Data_Analysis/test.json", 'r') as file:
    json_data=json.load(file)
print(json.dumps(json_data, indent="\t"))

{
	"K5": {
		"price": "5000",
		"year": "2015"
	},
	"Avante": {
		"price": "3000",
		"year": "2014"
	}
}


In [8]:
import json
with open("C:/Users/pc/Main/Data_Analysis/test1.json", 'r') as file:
    json_data=json.load(file)
friend =dict()
while True:
    print("================================")
    print("1. 친구 리스트 출력")
    print("2. 친구 추가")
    print("3. 친구 삭제")
    print("4. 이름 변경")
    print("5. 저장하기 ")
    print("9. 종료")
    menu=int(input("메뉴를 입력하세요 : "))
    if menu==1:
        print(json_data)
    elif menu ==2:
        name=input("이름을 입력하세요 : ")
        tel=input("전화번호를 입력하세요 : ")
        friend["name"]=name
        friend["tel"]=tel
        json_data[name]=friend
    elif menu ==3: #삭제
        name=input("이름을 입력하세요 : ")
        del json_data[name]
        print("친구 삭제 완료")
    elif menu ==4: #수정
        name=input("이름을 입력하세요 : ")
        tel=input("전화번호를 입력하세요 : ")
        json_data[name]["name"]=name
        json_data[name]["tel"]=tel
        print("친구 수정완료")
    elif menu ==5:
        with open("C:/Users/pc/Main/Data_Analysis/test1.json", "w") as make_file:
            json.dump(json_data, make_file, indent="\t")
    elif menu == 9:
        break
    else:
        print("다시 입력해주세요")
print("시스템 종료")


1. 친구 리스트 출력
2. 친구 추가
3. 친구 삭제
4. 이름 변경
5. 저장하기 
9. 종료
메뉴를 입력하세요 : 1
{'tom': {'name': 'tom', 'tel': '011'}, 'Avante': {'name': 'avante', 'tel': '2014'}, 'james': {'name': 'james', 'tel': '235'}}
1. 친구 리스트 출력
2. 친구 추가
3. 친구 삭제
4. 이름 변경
5. 저장하기 
9. 종료
메뉴를 입력하세요 : 9
시스템 종료


## xml 활용하기

In [11]:
from xml.etree.ElementTree import parse

tree=parse("test.xml") #xml파일 불러오기
root = tree.getroot()

student = root.findall("student") #student를 찾아..

name = [x.findtext("name") for x in student]
age =  [x.findtext("age") for x in student]
score =  [x.find("score").attrib for x in student]

print(name)
print(age)
print(score)

['peter', 'elgar', 'hong']
['24', '21', '36']
[{'math': '80', 'english': '97'}, {'math': '67', 'english': '56'}, {'math': '76', 'english': '81'}]


## yml 활용하기

In [33]:
import yaml

with open("vegetables.yml") as f:
    vegetables=yaml.load(f, Loader=yaml.FullLoader)
    print(vegetables)

{'Vegetables': ['Pepper', 'Tomato', 'Garlic']}


In [41]:
import yaml

with open("cars.yml") as f:
    cars_original=yaml.load(f, Loader=yaml.FullLoader)
    print(cars_original)
    
    print("====================================")
    cars_sorted=yaml.dump(cars_original, sort_keys=True)
    print(cars_sorted)

{'hyundai': 45000, 'tesla': 65000, 'chevrolet': 42000, 'audi': 51000, 'mercedesbenz': 80000}
audi: 51000
chevrolet: 42000
hyundai: 45000
mercedesbenz: 80000
tesla: 65000



In [42]:
with open("cars.yml") as f:
    cars_original=yaml.load(f, Loader=yaml.FullLoader)
    print(cars_original)
    
    print("====================================")
    for key, value in sorted(cars_original.items(), key=lambda item : item[1]):
        print(key, ":", value)

{'hyundai': 45000, 'tesla': 65000, 'chevrolet': 42000, 'audi': 51000, 'mercedesbenz': 80000}
chevrolet : 42000
hyundai : 45000
audi : 51000
tesla : 65000
mercedesbenz : 80000


In [44]:
fruits={"fruits":["blubbery", "apple","oragne"]}

with open("fruits.yml", "w") as f:
    yaml.dump(fruits, f)

# Numpy

In [56]:
import numpy as np


def pprint(arr):
    print("type: {}".format(type(arr)))
    print("shape: {}".format(arr.shape))
    print("Array's Data:\n{}".format(arr))
    
arr=[1,2,3]
a=np.array(arr)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3,)
Array's Data:
[1 2 3]


In [60]:
arr=[(1,2,3),(4,5,6)]
b=np.array(arr, dtype=float)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 3)
Array's Data:
[[1. 2. 3.]
 [4. 5. 6.]]


In [59]:
arr=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
c=np.array(arr, dtype=float)
pprint(c)

type: <class 'numpy.ndarray'>
shape: (2, 2, 3)
Array's Data:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [65]:
a=np.zeros((3,2))
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 2)
Array's Data:
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [68]:
b = [[1,2,3],[4,5,6],[7,8,9]]
c=np.zeros_like(b) #b의 shape로 값은 0으로 넣음
pprint(c)

type: <class 'numpy.ndarray'>
shape: (3, 3)
Array's Data:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [71]:
b = [[1,2,3],[4,5,6],[7,8,9]]
c=np.ones_like(b, dtype=float) #b의 shape로 값은 1으로 넣음
pprint(c)

type: <class 'numpy.ndarray'>
shape: (3, 3)
Array's Data:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [70]:
a=np.ones((3,2))
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 2)
Array's Data:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [73]:
a = np.array(range(10))
pprint(a)

type: <class 'numpy.ndarray'>
shape: (10,)
Array's Data:
[0 1 2 3 4 5 6 7 8 9]


In [76]:
b=a.reshape(-1,5)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 5)
Array's Data:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [77]:
b=a.reshape(2,-1,5)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 1, 5)
Array's Data:
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
